apiVersion: v1
kind: ConfigMap
metadata:
  name: pocetna-strana
data:
 index.html: |
  <!DOCTYPE html>
  <html lang="en">
  <head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Greška</title>
  </head>
  <body>
      <h1>Dobro dosli u Cetin</h1>
      <p>Ako neko ima neke pitanje moze da ga postavi </p>
  </body>
  </html>
